"use client";

// import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { MyThemeContextProvider } from "./store/store";

// export const metadata: Metadata = {
//   title: "Next Weather App",
//   description: "Generated by create next app",
// };

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  style: ["normal", "italic"],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const queryClient = new QueryClient();
  return (
    <html lang="en">
      <MyThemeContextProvider>
        <QueryClientProvider client={queryClient}>
          <body className={poppins.className}>{children}</body>
        </QueryClientProvider>
      </MyThemeContextProvider>
    </html>
  );
}
